export const ADD_COMMENT = 'ADD_COMMENT';

export const PLANTS_LOADING = 'PLANTS_LOADING';
export const PLANTS_FAILED = 'PLANTS_FAILED';
export const ADD_PLANTS = 'ADD_PLANTS';

export const ADD_COMMENTS = 'ADD_COMMENTS';
export const COMMENTS_FAILED = 'COMMENTS_FAILED';
export const PROMOS_LOADING = 'PROMOS_LOADING';
export const ADD_PROMOS = 'ADD_PROMOS';
export const PROMOS_FAILED = 'PROMOS_FAILED';